//
// AssetsResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "OpenAPIClientAPI.AssetsResponseDto")
public typealias AssetsResponseDto = OpenAPIClientAPI.AssetsResponseDto

extension OpenAPIClientAPI {

public struct AssetsResponseDto: Codable, JSONEncodable, Hashable {

    /** Number of assets to return per page */
    public var items: [Asset]
    /** Number of total items */
    public var total: Double
    /** Number of items to return per page */
    public var limit: Double
    /** Page number */
    public var page: Double

    public init(items: [Asset], total: Double, limit: Double, page: Double) {
        self.items = items
        self.total = total
        self.limit = limit
        self.page = page
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case items
        case total
        case limit
        case page
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(items, forKey: .items)
        try container.encode(total, forKey: .total)
        try container.encode(limit, forKey: .limit)
        try container.encode(page, forKey: .page)
    }
}

}
