//
// SetContractUriInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "OpenAPIClientAPI.SetContractUriInput")
public typealias SetContractUriInput = OpenAPIClientAPI.SetContractUriInput

extension OpenAPIClientAPI {

public struct SetContractUriInput: Codable, JSONEncodable, Hashable {

    /** Game Id */
    public var gameId: String
    /** Collection Id */
    public var collectionId: String
    /** Contract URI */
    public var contractUri: String

    public init(gameId: String, collectionId: String, contractUri: String) {
        self.gameId = gameId
        self.collectionId = collectionId
        self.contractUri = contractUri
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case gameId = "game_id"
        case collectionId = "collection_id"
        case contractUri = "contract_uri"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(gameId, forKey: .gameId)
        try container.encode(collectionId, forKey: .collectionId)
        try container.encode(contractUri, forKey: .contractUri)
    }
}

}
