//
// SetContractUriDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "OpenAPIClientAPI.SetContractUriDto")
public typealias SetContractUriDto = OpenAPIClientAPI.SetContractUriDto

extension OpenAPIClientAPI {

public struct SetContractUriDto: Codable, JSONEncodable, Hashable {

    /** Project Id */
    public var projectId: String
    /** Collection Id */
    public var collectionId: String
    /** Contract URI */
    public var contractUri: String

    public init(projectId: String, collectionId: String, contractUri: String) {
        self.projectId = projectId
        self.collectionId = collectionId
        self.contractUri = contractUri
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case projectId = "project_id"
        case collectionId = "collection_id"
        case contractUri = "contract_uri"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(projectId, forKey: .projectId)
        try container.encode(collectionId, forKey: .collectionId)
        try container.encode(contractUri, forKey: .contractUri)
    }
}

}
