//
// SetSaleStatusInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "OpenAPIClientAPI.SetSaleStatusInput")
public typealias SetSaleStatusInput = OpenAPIClientAPI.SetSaleStatusInput

extension OpenAPIClientAPI {

public struct SetSaleStatusInput: Codable, JSONEncodable, Hashable {

    /** Game Id */
    public var gameId: String
    /** Collection Id */
    public var collectionId: String
    /** Sale Status of the contract */
    public var saleStatus: AnyCodable

    public init(gameId: String, collectionId: String, saleStatus: AnyCodable) {
        self.gameId = gameId
        self.collectionId = collectionId
        self.saleStatus = saleStatus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case gameId = "game_id"
        case collectionId = "collection_id"
        case saleStatus = "sale_status"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(gameId, forKey: .gameId)
        try container.encode(collectionId, forKey: .collectionId)
        try container.encode(saleStatus, forKey: .saleStatus)
    }
}

}
