//
// SetSaleStatusDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "OpenAPIClientAPI.SetSaleStatusDto")
public typealias SetSaleStatusDto = OpenAPIClientAPI.SetSaleStatusDto

extension OpenAPIClientAPI {

public struct SetSaleStatusDto: Codable, JSONEncodable, Hashable {

    /** Project Id */
    public var projectId: String
    /** Collection Id */
    public var collectionId: String
    /** Sale Status of the contract */
    public var saleStatus: AnyCodable

    public init(projectId: String, collectionId: String, saleStatus: AnyCodable) {
        self.projectId = projectId
        self.collectionId = collectionId
        self.saleStatus = saleStatus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case projectId = "project_id"
        case collectionId = "collection_id"
        case saleStatus = "sale_status"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(projectId, forKey: .projectId)
        try container.encode(collectionId, forKey: .collectionId)
        try container.encode(saleStatus, forKey: .saleStatus)
    }
}

}
