//
// TransactionAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import RxSwift
#if canImport(AnyCodable)
import AnyCodable
#endif

extension OpenAPIClientAPI {


open class TransactionAPI {

    /**
     Retrieve Transaction by ID
     
     - parameter authorization: (header) API key is associated with multiple games. Please include it in to use developers API. 
     - parameter id: (path)  
     - parameter gameId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Observable<Transaction>
     */
    open class func getTransactionById(authorization: String, id: String, gameId: String, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue) -> Observable<Transaction> {
        return Observable.create { observer -> Disposable in
            let requestTask = getTransactionByIdWithRequestBuilder(authorization: authorization, id: id, gameId: gameId).execute(apiResponseQueue) { result in
                switch result {
                case let .success(response):
                    observer.onNext(response.body)
                case let .failure(error):
                    observer.onError(error)
                }
                observer.onCompleted()
            }
            
            return Disposables.create {
                requestTask.cancel()
            }
        }
    }

    /**
     Retrieve Transaction by ID
     
     - parameter authorization: (header) API key is associated with multiple games. Please include it in to use developers API. 
     - parameter id: (path)  
     - parameter gameId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the result
     */
    @discardableResult
    open class func getTransactionById(authorization: String, id: String, gameId: String, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ result: Swift.Result<Transaction, ErrorResponse>) -> Void)) -> RequestTask {
        return getTransactionByIdWithRequestBuilder(authorization: authorization, id: id, gameId: gameId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(.success(response.body))
            case let .failure(error):
                completion(.failure(error))
            }
        }
    }

    /**
     Retrieve Transaction by ID
     - GET /v1/transaction/{game_id}/{id}
     - Retrieve transaction by ID
     - parameter authorization: (header) API key is associated with multiple games. Please include it in to use developers API. 
     - parameter id: (path)  
     - parameter gameId: (path)  
     - returns: RequestBuilder<Transaction> 
     */
    open class func getTransactionByIdWithRequestBuilder(authorization: String, id: String, gameId: String) -> RequestBuilder<Transaction> {
        var localVariablePath = "/v1/transaction/{game_id}/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let gameIdPreEscape = "\(APIHelper.mapValueToPathItem(gameId))"
        let gameIdPostEscape = gameIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{game_id}", with: gameIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Authorization": authorization.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Transaction>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     * enum for parameter order
     */
    public enum Order_getTransactions: String, CaseIterable {
        case asc = "ASC"
        case desc = "DESC"
    }

    /**
     Retrieve transactions
     
     - parameter authorization: (header) API key is associated with multiple games. Please include it in to use developers API. 
     - parameter gameId: (query) Game ID to find transactions in your game. Example: Fortnite, Minecraft, etc. 
     - parameter collectionId: (query) Filter transactions by collection. Example: Get transactions only from Weapons collection. (optional)
     - parameter playerId: (query) Player ID to mint to. You can provide player ID or player address (optional)
     - parameter sort: (query) Asset field to sort by. You can sort by name, created_on and etc. (optional)
     - parameter order: (query) Sort order (ASC for ascending or DESC for descending) (optional)
     - parameter searchText: (query) Search transactions by name (optional)
     - parameter limit: (query) Number of transactions to return per page (optional)
     - parameter page: (query) Page number (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Observable<Transaction>
     */
    open class func getTransactions(authorization: String, gameId: String, collectionId: String? = nil, playerId: String? = nil, sort: String? = nil, order: Order_getTransactions? = nil, searchText: String? = nil, limit: Double? = nil, page: Double? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue) -> Observable<Transaction> {
        return Observable.create { observer -> Disposable in
            let requestTask = getTransactionsWithRequestBuilder(authorization: authorization, gameId: gameId, collectionId: collectionId, playerId: playerId, sort: sort, order: order, searchText: searchText, limit: limit, page: page).execute(apiResponseQueue) { result in
                switch result {
                case let .success(response):
                    observer.onNext(response.body)
                case let .failure(error):
                    observer.onError(error)
                }
                observer.onCompleted()
            }
            
            return Disposables.create {
                requestTask.cancel()
            }
        }
    }

    /**
     Retrieve transactions
     
     - parameter authorization: (header) API key is associated with multiple games. Please include it in to use developers API. 
     - parameter gameId: (query) Game ID to find transactions in your game. Example: Fortnite, Minecraft, etc. 
     - parameter collectionId: (query) Filter transactions by collection. Example: Get transactions only from Weapons collection. (optional)
     - parameter playerId: (query) Player ID to mint to. You can provide player ID or player address (optional)
     - parameter sort: (query) Asset field to sort by. You can sort by name, created_on and etc. (optional)
     - parameter order: (query) Sort order (ASC for ascending or DESC for descending) (optional)
     - parameter searchText: (query) Search transactions by name (optional)
     - parameter limit: (query) Number of transactions to return per page (optional)
     - parameter page: (query) Page number (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the result
     */
    @discardableResult
    open class func getTransactions(authorization: String, gameId: String, collectionId: String? = nil, playerId: String? = nil, sort: String? = nil, order: Order_getTransactions? = nil, searchText: String? = nil, limit: Double? = nil, page: Double? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ result: Swift.Result<Transaction, ErrorResponse>) -> Void)) -> RequestTask {
        return getTransactionsWithRequestBuilder(authorization: authorization, gameId: gameId, collectionId: collectionId, playerId: playerId, sort: sort, order: order, searchText: searchText, limit: limit, page: page).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(.success(response.body))
            case let .failure(error):
                completion(.failure(error))
            }
        }
    }

    /**
     Retrieve transactions
     - GET /v1/transaction
     - Retrieve all transactions.
     - parameter authorization: (header) API key is associated with multiple games. Please include it in to use developers API. 
     - parameter gameId: (query) Game ID to find transactions in your game. Example: Fortnite, Minecraft, etc. 
     - parameter collectionId: (query) Filter transactions by collection. Example: Get transactions only from Weapons collection. (optional)
     - parameter playerId: (query) Player ID to mint to. You can provide player ID or player address (optional)
     - parameter sort: (query) Asset field to sort by. You can sort by name, created_on and etc. (optional)
     - parameter order: (query) Sort order (ASC for ascending or DESC for descending) (optional)
     - parameter searchText: (query) Search transactions by name (optional)
     - parameter limit: (query) Number of transactions to return per page (optional)
     - parameter page: (query) Page number (optional)
     - returns: RequestBuilder<Transaction> 
     */
    open class func getTransactionsWithRequestBuilder(authorization: String, gameId: String, collectionId: String? = nil, playerId: String? = nil, sort: String? = nil, order: Order_getTransactions? = nil, searchText: String? = nil, limit: Double? = nil, page: Double? = nil) -> RequestBuilder<Transaction> {
        let localVariablePath = "/v1/transaction"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "game_id": (wrappedValue: gameId.encodeToJSON(), isExplode: true),
            "collection_id": (wrappedValue: collectionId?.encodeToJSON(), isExplode: true),
            "player_id": (wrappedValue: playerId?.encodeToJSON(), isExplode: true),
            "sort": (wrappedValue: sort?.encodeToJSON(), isExplode: true),
            "order": (wrappedValue: order?.encodeToJSON(), isExplode: true),
            "search_text": (wrappedValue: searchText?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Authorization": authorization.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Transaction>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
}
